---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse 

- src: git@github.com:rootnoir/netology-ansible-vector-role.git
  scm: git
  version: "1.0.0"
  name: vector-role  

- src: git@github.com:rootnoir/netology-ansible-lighthouse-role.git
  scm: git
  version: "1.0.1"
  name: lighthouse-role

